CREATE TABLESPACE reporting_data
  DATAFILE '/u01/dbfile/O12C/reporting_data01.dbf' SIZE 1G
  EXTENT MANAGEMENT LOCAL
  UNIFORM SIZE 1M
  SEGMENT SPACE MANAGEMENT AUTO;
--
CREATE TABLESPACE reporting_index
  DATAFILE '/u01/dbfile/O12C/reporting_index01.dbf' SIZE 500M
  EXTENT MANAGEMENT LOCAL
  UNIFORM SIZE 128K
  SEGMENT SPACE MANAGEMENT AUTO;

